### ISSUE TITLE
Issue with getRuleSet3 needing Python 3.6

### ISSUE THREAD

**Issue by alessa-weiler** [crisprVerse/crisprScore#12]
Hey JP - I've been struggling with getting getRuleSet3() to work. I'm able to get rule set 1 scores and have formatted my data to have the correct spacers, but it seems like the issue may be more about connecting with python 3.6

I'm working from a mac with an M1 chip. I wonder whether this is the issue, as python 3.6 isn't available for my computer. 

When I try to run the example as part of the package, I get the same error message as when I run it on my data. here is the error message that I get:

`> ?getRuleSet3Scores
PREFIX=/Users/Coding/Library/Caches/org.R-project.R/R/basilisk/1.14.2/0
Unpacking payload ...
Collecting package metadata (current_repodata.json): ...working... done                                        
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/Coding/Library/Caches/org.R-project.R/R/basilisk/1.14.2/0

  added / updated specs:
    - brotlipy==0.7.0=py39h1a28f6b_1002
    - ca-certificates==2022.4.26=hca03da5_0
    - certifi==2022.5.18.1=py39hca03da5_0
    - cffi==1.15.0=py39h22df2f2_1
    - charset-normalizer==2.0.4=pyhd3eb1b0_0
    - conda-content-trust==0.1.1=pyhd3eb1b0_0
    - conda-package-handling==1.8.1=py39h1a28f6b_0
    - conda==4.12.0=py39hca03da5_0
    - cryptography==37.0.1=py39h834c97f_0
    - idna==3.3=pyhd3eb1b0_0
    - libcxx==12.0.0=hf6beb65_1
    - libffi==3.4.2=hc377ac9_2
    - ncurses==6.3=h1a28f6b_2
    - openssl==1.1.1o=h1a28f6b_0
    - pip==21.2.4=py39hca03da5_0
    - pycosat==0.6.3=py39h1a28f6b_0
    - pycparser==2.21=pyhd3eb1b0_0
    - pyopenssl==22.0.0=pyhd3eb1b0_0
    - pysocks==1.7.1=py39hca03da5_0
    - python.app==3=py39h1a28f6b_0
    - python==3.9.12=hbdb9e5c_0
    - readline==8.1.2=h1a28f6b_1
    - requests==2.27.1=pyhd3eb1b0_0
    - ruamel_yaml==0.15.100=py39h1a28f6b_0
    - setuptools==61.2.0=py39hca03da5_0
    - six==1.16.0=pyhd3eb1b0_1
    - sqlite==3.38.3=h1058600_0
    - tk==8.6.11=hb8d0fd4_1
    - tqdm==4.64.0=py39hca03da5_0
    - tzdata==2022a=hda174b7_0
    - urllib3==1.26.9=py39hca03da5_0
    - wheel==0.37.1=pyhd3eb1b0_0
    - xz==5.2.5=h1a28f6b_1
    - yaml==0.2.5=h1a28f6b_0
    - zlib==1.2.12=h5a0b063_2

The following NEW packages will be INSTALLED:

  brotlipy           pkgs/main/osx-arm64::brotlipy-0.7.0-py39h1a28f6b_1002
  ca-certificates    pkgs/main/osx-arm64::ca-certificates-2022.4.26-hca03da5_0
  certifi            pkgs/main/osx-arm64::certifi-2022.5.18.1-py39hca03da5_0
  cffi               pkgs/main/osx-arm64::cffi-1.15.0-py39h22df2f2_1
  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0
  conda              pkgs/main/osx-arm64::conda-4.12.0-py39hca03da5_0
  conda-content-tru~ pkgs/main/noarch::conda-content-trust-0.1.1-pyhd3eb1b0_0
  conda-package-han~ pkgs/main/osx-arm64::conda-package-handling-1.8.1-py39h1a28f6b_0
  cryptography       pkgs/main/osx-arm64::cryptography-37.0.1-py39h834c97f_0
  idna               pkgs/main/noarch::idna-3.3-pyhd3eb1b0_0
  libcxx             pkgs/main/osx-arm64::libcxx-12.0.0-hf6beb65_1
  libffi             pkgs/main/osx-arm64::libffi-3.4.2-hc377ac9_2
  ncurses            pkgs/main/osx-arm64::ncurses-6.3-h1a28f6b_2
  openssl            pkgs/main/osx-arm64::openssl-1.1.1o-h1a28f6b_0
  pip                pkgs/main/osx-arm64::pip-21.2.4-py39hca03da5_0
  pycosat            pkgs/main/osx-arm64::pycosat-0.6.3-py39h1a28f6b_0
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0
  pyopenssl          pkgs/main/noarch::pyopenssl-22.0.0-pyhd3eb1b0_0
  pysocks            pkgs/main/osx-arm64::pysocks-1.7.1-py39hca03da5_0
  python             pkgs/main/osx-arm64::python-3.9.12-hbdb9e5c_0
  python.app         pkgs/main/osx-arm64::python.app-3-py39h1a28f6b_0
  readline           pkgs/main/osx-arm64::readline-8.1.2-h1a28f6b_1
  requests           pkgs/main/noarch::requests-2.27.1-pyhd3eb1b0_0
  ruamel_yaml        pkgs/main/osx-arm64::ruamel_yaml-0.15.100-py39h1a28f6b_0
  setuptools         pkgs/main/osx-arm64::setuptools-61.2.0-py39hca03da5_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  sqlite             pkgs/main/osx-arm64::sqlite-3.38.3-h1058600_0
  tk                 pkgs/main/osx-arm64::tk-8.6.11-hb8d0fd4_1
  tqdm               pkgs/main/osx-arm64::tqdm-4.64.0-py39hca03da5_0
  tzdata             pkgs/main/noarch::tzdata-2022a-hda174b7_0
  urllib3            pkgs/main/osx-arm64::urllib3-1.26.9-py39hca03da5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-arm64::xz-5.2.5-h1a28f6b_1
  yaml               pkgs/main/osx-arm64::yaml-0.2.5-h1a28f6b_0
  zlib               pkgs/main/osx-arm64::zlib-1.2.12-h5a0b063_2

Preparing transaction: ...working... done
Executing transaction: ...working... 
done
installation finished.
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.7.7

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by Jfortin1** [comment]
Hi @alessa-weiler, unfortunately the original code was developed on a python version that is not supporting M1, and we don't have the bandwidth to refactor their code / test their code on M1 chip on a different python environment. I'd recommend running the code on a different unix environment.
