### ISSUE TITLE
On-target scores for SaCas9

### ISSUE THREAD

**Issue by Chenmy38** [crisprVerse/crisprScore#16]
Hi! Thanks for developing such a comprehensive tool for sgRNA design. I am wondering if it is possible to add on-target scores for SaCas9 using models like Azimuth 2.0 or something else. It will be very helpful!

**Comment by Jfortin1** [comment]
Hi @Chenmy38, if there is an existing algorithm for SaCas9 prediction, we can implement it, but we (our team) do not have the capacity to develop our own algorithms
