### ISSUE TITLE
Issue with DeepCpf1, enPAM+GB score example

### ISSUE THREAD

**Issue by ericmalekos** [crisprVerse/crisprScore#18]
Hi @Jfortin1 

I notice there is a discrepancy in the DeepCpf1 example
The example command is:

```
flank5 <- "ACC" #3bp
pam    <- "TTTT" #4bp
spacer <- "AATCGATGCTGATGCTAGATATT" #23bp
flank3 <- "AAGT" #4bp
input  <- paste0(flank5, pam, spacer, flank3) 
results <- getDeepCpf1Scores(input)
```
While the image shows a 4pb flank5 and a 2bp flank3. Also, the image length is 33 bps but the input should be 34 bps.

I think they are both incorrect and it should be:
`flank5 #4bp` and `flank3 #3 bp`

There may be a similar issue with the enPAM+GB example.

**Comment by Jfortin1** [comment]
Thanks for catching this! Fixed in 1.9.3 @ericmalekos 
crisprDesign is unaffected as it used the correct flanking sequences using the roster in /crisprScore/inst/roster to extract the flanking sequences
