### ISSUE TITLE
Error with addOnTargetScores

### ISSUE THREAD

**Issue by AudreyDub** [crisprVerse/crisprScore#6]
Hi,
Actually i use a custom nuclease sequence define like this:

```
nuc<- CrisprNuclease("nuc",
                           targetType="DNA",
                           pams="VVVTTTV(21/26)",
                           metadata=list(description="Custom nuclease."),
                           pam_side="5prime",
                           spacer_length=23)
                           
gs <- findSpacers(dna, crisprNuclease=nuc)
gs<- addOnTargetScores(gs, methods="enpamgb") 
Error in .validateOnTargetScoreMethods(methods = methods, crisprNuclease = crisprNuclease) : 
  No scoring method found for crisprNuclease
```
  
How can i define a correct method for my custom nuclease?

At the end, the idea is to obtain a GuideSet with on/Off target :)

Thx
Audrey

**Comment by Jfortin1** [comment]
Hi @AudreyDub,

The on- and off-target scoring algorithms were developed for specific nucleases (enPAMGV was developed for the engineered Cas12a for instance), so `addOnTargetScores` and `addOffTargetScores` cannot be used for your custom nuclease.
