### ISSUE TITLE
python 2.7 issue

### ISSUE THREAD

**Issue by xguo-nveloptx** [crisprVerse/crisprScore#9]
Hi,
Thanks for making the package available. I try to use the addOnTargetScore function, but ran into the complain about python 2.7 is not available in current conda channel. Could you please suggest a way to work around it?

Thanks

Xiaoyun

**Comment by Jfortin1** [comment]
Hi @xguo-nveloptx, which scoring methods are you using (please provide your exact code)? Could you provide your `sessionInfo()` output as well?

**Comment by Jfortin1** [comment]
@xguo-nveloptx We have fixed a few bugs today; could you try 1.7.2 of the devel branch to see if you have the same problems?

**Comment by Jfortin1** [comment]
@xguo-nveloptx Any updates?

**Comment by codingrookie123** [comment]
Hi, first of all , thank you for making such a detailed tutorial!
I had a similar problem, where azimuth, lindel and other scoring methods that depend on python 2.7 did not work in my local computer. I saw another comment you posted on a previous issue-post refering to how these scoring algorithms cannot be run on a M1 machine and was wondering if that is the issue as my computer is a Apple M1 Max. Is there no work-around?
 
This is the conda channel on my local computer for your reference :
(base) 01-5651:$ conda install python=2.7
(base) 01-5651:$ conda config --add subdirs osx-64
(base) 01-5651:$ conda search python
Loading channels: done
 Name                       Version           Build  Channel             
python                        2.7.13     h32f5f24_13  pkgs/main           
python                        2.7.13     h89fad4f_16  pkgs/main           
python                        2.7.13     hdada7c8_15  pkgs/main           
python                        2.7.14     h001abdc_23  pkgs/main           
python                        2.7.14     h138c1fe_30  pkgs/main           
python                        2.7.14     h138c1fe_31  pkgs/main           
python                        2.7.14     h50fefbe_18  pkgs/main           
python                        2.7.14     ha6acbcf_22  pkgs/main           
python                        2.7.14     ha7e29e4_26  pkgs/main           
python                        2.7.14     hd74e306_15  pkgs/main           
python                        2.7.14     hde5916a_29  pkgs/main           
python                        2.7.14     he768d2d_19  pkgs/main           
python                        2.7.14     hed931fe_16  pkgs/main           
python                        2.7.15      h138c1fe_0  pkgs/main           
python                        2.7.15      h8f8e585_2  pkgs/main           
python                        2.7.15      h8f8e585_4  pkgs/main           
python                        2.7.15      h8f8e585_6  pkgs/main           
python                        2.7.16      h97142e2_0  pkgs/main           
python                        2.7.16      h97142e2_1  pkgs/main           
python                        2.7.16      h97142e2_2  pkgs/main           
python                        2.7.16      h97142e2_3  pkgs/main           
python                        2.7.16      h97142e2_4  pkgs/main           
python                        2.7.16      h97142e2_5  pkgs/main           
python                        2.7.16      h97142e2_6  pkgs/main           
python                        2.7.16      h97142e2_7  pkgs/main           
python                        2.7.17      h97142e2_0  pkgs/main           
python                        2.7.18      h441ce09_3  pkgs/main           
python                        2.7.18      h47d645e_1  pkgs/main           
python                        2.7.18      hc817775_0  pkgs/main           
python                         3.5.4     h4bd9b1b_18  pkgs/main           
python                         3.5.4     h821eb87_14  pkgs/main           
python                         3.5.4     h8f450c2_22  pkgs/main           
python                         3.5.4     hb8880cc_19  pkgs/main           
python                         3.5.4     hc167b69_27  pkgs/main           
python                         3.5.4     hdd9bdb2_21  pkgs/main           
python                         3.5.4     he1de2d4_12  pkgs/main           
python                         3.5.4     he720263_23  pkgs/main           
python                         3.5.4     hf91e954_15  pkgs/main           
python                         3.5.5      h0a44026_3  pkgs/main           
python                         3.5.5      hc167b69_0  pkgs/main           
python                         3.5.5      hc167b69_1  pkgs/main           
python                         3.5.6      hc167b69_0  pkgs/main           
python                         3.6.2     h26d10c0_12  pkgs/main           
python                         3.6.2     h9e63aee_14  pkgs/main           
python                         3.6.2     ha11d96e_18  pkgs/main           
python                         3.6.2     hd04bb42_19  pkgs/main           
python                         3.6.2     hd0bf7f1_15  pkgs/main           
python                         3.6.3      h47c878a_7  pkgs/main           
python                         3.6.3      h5ce8c04_4  pkgs/main           
python                         3.6.3      h6804ab2_0  pkgs/main           
python                         3.6.3      h794556d_2  pkgs/main           
python                         3.6.3      hc655967_3  pkgs/main           
python                         3.6.4      hc167b69_0  pkgs/main           
python                         3.6.4      hc167b69_1  pkgs/main           
python                         3.6.4      hc167b69_3  pkgs/main           
python                         3.6.5      hc167b69_0  pkgs/main           
python                         3.6.5      hc167b69_1  pkgs/main           
python                         3.6.6      hc167b69_0  pkgs/main           
python                         3.6.7      haf84260_0  pkgs/main           
python                         3.6.8      haf84260_0  pkgs/main           
python                         3.6.9      h359304d_0  pkgs/main           
python                        3.6.10      h359304d_0  pkgs/main           
python                        3.6.10      hc70fcce_1  pkgs/main           
python                        3.6.10      hf48f09d_2  pkgs/main           
python                        3.6.10      hfe9666f_1  pkgs/main           
python                        3.6.12      h26836e1_2  pkgs/main           
python                        3.6.13      h88f2d9e_0  pkgs/main           
python                         3.7.0      hc167b69_0  pkgs/main           
python                         3.7.1      haf84260_3  pkgs/main           
python                         3.7.1      haf84260_7  pkgs/main           
python                         3.7.2      haf84260_0  pkgs/main           
python                         3.7.3      h359304d_0  pkgs/main           
python                         3.7.4      h359304d_0  pkgs/main           
python                         3.7.4      h359304d_1  pkgs/main           
python                         3.7.5      h359304d_0  pkgs/main           
python                         3.7.6      h359304d_2  pkgs/main           
python                         3.7.7 hc70fcce_0_cpython  pkgs/main           
python                         3.7.7      hf48f09d_4  pkgs/main           
python                         3.7.7 hfe9666f_0_cpython  pkgs/main           
python                         3.7.9      h26836e1_0  pkgs/main           
python                        3.7.10      h88f2d9e_0  pkgs/main           
python                        3.7.11      h88f2d9e_0  pkgs/main           
python                        3.7.13      hdfd78df_0  pkgs/main           
python                        3.7.13      hdfd78df_1  pkgs/main           
python                        3.7.15      h218abb5_1  pkgs/main           
python                        3.7.15      h4319210_0  pkgs/main           
python                        3.7.16      h218abb5_0  pkgs/main           
python                         3.8.0      h359304d_0  pkgs/main           
python                         3.8.0      h359304d_1  pkgs/main           
python                         3.8.0      h359304d_2  pkgs/main           
python                         3.8.1      h359304d_1  pkgs/main           
python                         3.8.2      hc70fcce_0  pkgs/main           
python                         3.8.2     hf48f09d_13  pkgs/main           
python                         3.8.2      hfe9666f_0  pkgs/main           
python                         3.8.3      h26836e1_1  pkgs/main           
python                         3.8.3      h26836e1_2  pkgs/main           
python                         3.8.5      h26836e1_0  pkgs/main           
python                         3.8.5      h26836e1_1  pkgs/main           
python                         3.8.8      h88f2d9e_4  pkgs/main           
python                         3.8.8      h88f2d9e_5  pkgs/main           
python                        3.8.10      h88f2d9e_7  pkgs/main           
python                        3.8.11      h88f2d9e_1  pkgs/main           
python                        3.8.12      h88f2d9e_0  pkgs/main           
python                        3.8.13      hdfd78df_0  pkgs/main           
python                        3.8.13      hdfd78df_1  pkgs/main           
python                        3.8.15      h218abb5_2  pkgs/main           
python                        3.8.15      h4319210_0  pkgs/main           
python                        3.8.16      h218abb5_2  pkgs/main           
python                        3.8.16      h218abb5_3  pkgs/main           
python                        3.8.16      h5ee71fb_4  pkgs/main           
python                        3.8.17      h218abb5_0  pkgs/main           
python                        3.8.17      h5ee71fb_0  pkgs/main           
python                        3.8.18      h218abb5_0  pkgs/main           
python                        3.8.18      h5ee71fb_0  pkgs/main           
python                         3.9.0      h88f2d9e_1  pkgs/main           
python                         3.9.0      h88f2d9e_2  pkgs/main           
python                         3.9.1      h88f2d9e_2  pkgs/main           
python                         3.9.2      h88f2d9e_0  pkgs/main           
python                         3.9.4      h88f2d9e_0  pkgs/main           
python                         3.9.5      h88f2d9e_3  pkgs/main           
python                         3.9.6      h88f2d9e_0  pkgs/main           
python                         3.9.6      h88f2d9e_1  pkgs/main           
python                         3.9.7      h88f2d9e_1  pkgs/main           
python                        3.9.11      hdfd78df_1  pkgs/main           
python                        3.9.11      hdfd78df_2  pkgs/main           
python                        3.9.12      hdfd78df_0  pkgs/main           
python                        3.9.12      hdfd78df_1  pkgs/main           
python                        3.9.13      hdfd78df_1  pkgs/main           
python                        3.9.13      hdfd78df_2  pkgs/main           
python                        3.9.15      h218abb5_2  pkgs/main           
python                        3.9.15      hdfd78df_0  pkgs/main           
python                        3.9.16      h218abb5_0  pkgs/main           
python                        3.9.16      h218abb5_1  pkgs/main           
python                        3.9.16      h218abb5_2  pkgs/main           
python                        3.9.16      h5ee71fb_3  pkgs/main           
python                        3.9.17      h218abb5_0  pkgs/main           
python                        3.9.17      h5ee71fb_0  pkgs/main           
python                        3.9.18      h218abb5_0  pkgs/main           
python                        3.9.18      h5ee71fb_0  pkgs/main           
python                        3.10.0      h88f2d9e_0  pkgs/main           
python                        3.10.0      h88f2d9e_1  pkgs/main           
python                        3.10.0      hdfd78df_2  pkgs/main           
python                        3.10.0      hdfd78df_3  pkgs/main           
python                        3.10.0      hdfd78df_5  pkgs/main           
python                        3.10.3      hdfd78df_5  pkgs/main           
python                        3.10.4      hdfd78df_0  pkgs/main           
python                        3.10.6      hdfd78df_0  pkgs/main           
python                        3.10.6      hdfd78df_1  pkgs/main           
python                        3.10.8      h218abb5_1  pkgs/main           
python                        3.10.8      hdfd78df_0  pkgs/main           
python                        3.10.9      h218abb5_0  pkgs/main           
python                        3.10.9      h218abb5_1  pkgs/main           
python                        3.10.9      h218abb5_2  pkgs/main           
python                       3.10.10      h218abb5_2  pkgs/main           
python                       3.10.11      h218abb5_2  pkgs/main           
python                       3.10.11      h5ee71fb_3  pkgs/main           
python                       3.10.12      h218abb5_0  pkgs/main           
python                       3.10.12      h5ee71fb_0  pkgs/main           
python                       3.10.13      h218abb5_0  pkgs/main           
python                       3.10.13      h5ee71fb_0  pkgs/main           
python                        3.11.0      h1fd4e5f_2  pkgs/main           
python                        3.11.0      h1fd4e5f_3  pkgs/main           
python                        3.11.2      h1fd4e5f_0  pkgs/main           
python                        3.11.3      h1fd4e5f_0  pkgs/main           
python                        3.11.3      hf27a42d_1  pkgs/main           
python                        3.11.4      h1fd4e5f_0  pkgs/main           
python                        3.11.4      hf27a42d_0  pkgs/main           
python                        3.11.5      h1fd4e5f_0  pkgs/main           
python                        3.11.5      hf27a42d_0  pkgs/main           
python                        3.11.7      hf27a42d_0  pkgs/main           
python                        3.11.8      hf27a42d_0  pkgs/main           
python                        3.12.0      hd58486a_0  pkgs/main           
python                        3.12.1      hd58486a_0  pkgs/main           
python                        3.12.2      hd58486a_0  pkgs/main      

**and even after downloading the development version of crisprScore (v.1.7.2) and crisprScoreData from this github
I still faced similar errors, shown below, please help!** 

> guideSet <- addOnTargetScores(guideSet, methods = c("azimuth", "ruleset1", "ruleset3", "lindel", "deephf", "deepspcas9", "crisprater"))
[addOnTargetScores] Adding azimuth scores. 

+ /Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/0/bin/conda 'create' '--yes' '--prefix' '/Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/crisprScore/1.7.2/azimuth_basilisk' 'python=2.7' '--quiet' '-c' 'bioconda' '-c' 'conda-forge'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/crisprScore/1.7.2/azimuth_basilisk

  added / updated specs:
    - python=2.7


The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2024.2.2-h8857fd0_0
  certifi            conda-forge/osx-64::certifi-2019.11.28-py27h8c360ce_1
  libcxx             conda-forge/osx-64::libcxx-16.0.6-hd57cbcb_0
  libffi             bioconda/osx-64::libffi-3.2.1-1
  libsqlite          conda-forge/osx-64::libsqlite-3.45.1-h92b6c6a_0
  libzlib            conda-forge/osx-64::libzlib-1.2.13-h8a1eda9_5
  ncurses            conda-forge/osx-64::ncurses-6.4-h93d8f39_2
  openssl            conda-forge/osx-64::openssl-1.1.1w-h8a1eda9_0
  pip                conda-forge/osx-64::pip-20.0.2-py27_1
  python             conda-forge/osx-64::python-2.7.15-h8e446fc_1011_cpython
  python_abi         conda-forge/osx-64::python_abi-2.7-1_cp27m
  readline           conda-forge/osx-64::readline-8.2-h9e318b2_1
  setuptools         conda-forge/osx-64::setuptools-44.0.0-py27_0
  sqlite             conda-forge/osx-64::sqlite-3.45.1-h7461747_0
  tk                 conda-forge/osx-64::tk-8.6.13-h1abcd95_1
  wheel              conda-forge/osx-64::wheel-0.34.2-py27_0
  zlib               conda-forge/osx-64::zlib-1.2.13-h8a1eda9_5


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ /Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/0/bin/conda 'install' '--yes' '--prefix' '/Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/crisprScore/1.7.2/azimuth_basilisk' 'python=2.7'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 24.1.2

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: /Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/crisprScore/1.7.2/azimuth_basilisk

  added / updated specs:
    - python=2.7


The following packages will be UPDATED:

  openssl            conda-forge::openssl-1.1.1w-h8a1eda9_0 --> pkgs/main::openssl-3.0.13-hca72f7f_0
  python             conda-forge::python-2.7.15-h8e446fc_1~ --> pkgs/main::python-2.7.18-hc817775_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2024.2.2~ --> pkgs/main::ca-certificates-2023.12.12-hecd8cb5_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ /Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/0/bin/conda 'install' '--yes' '--prefix' '/Users/dskuen/Library/Caches/org.R-project.R/R/basilisk/1.14.3/crisprScore/1.7.2/azimuth_basilisk' '-c' 'bioconda' '-c' 'conda-forge' 'python=2.7' 'python=2.7' 'biopython=1.74' 'certifi=2019.11.28' 'cycler=0.10.0' 'futures=3.3.0' 'kiwisolver=1.1.0' 'matplotlib=2.2.3' 'mmtf-python=1.1.2' 'nose=1.3.7' 'numpy=1.11.3' 'olefile=0.46' 'pandas=0.23.4' 'Pillow=6.2.1' 'pip=20.1.1' 'pyparsing=2.4.7' 'python-dateutil=2.8.1' 'pytz=2020.1' 'reportlab=3.5.42' 'scipy=1.2.1' 'setuptools=44.0.0' 'six=1.15.0' 'subprocess32=3.5.4' 'tornado=5.1.1' 'wheel=0.36.2'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mmtf-python=1.1.2
  - pytz=2020.1
  - pyparsing=2.4.7
  - wheel=0.36.2
  - python-dateutil=2.8.1

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/r/osx-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error: one or more Python packages failed to install [error code 1]

**Comment by Jfortin1** [comment]
@codingrookie123 Unfortunately Python 2.7
